# MPESA_CONSUMER_KEY: '6KFXm2dBOMtHIsQjRtKo6OnA8MwPVwZW'
# MPESA_CONSUMER_SECRET: 'yYLbzfKE1EbMOEG4'
# MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
# MPESA_SHORT_CODE: '174379'
# MPESA_INITIATOR_NAME: 'testapi'
# MPESA_INITIATOR_PASSWORD: 'Safaricom999!*!'
# CALLBACK_URL: 'https://1bd8-102-215-78-19.in.ngrok.io/payments'
# REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"
